"""Hybrid signal learning utilities for BAB identification and artifact export."""

from .data import (
    ExperimentData,
    TrainRolloutData,
    build_train_rollout_data,
    compute_valid_start_indices,
    load_protocol2_datasets,
    summarize_protocol2,
)
from .io import (
    aggregate_metric_rows,
    load_model_prediction_npz,
    make_run_dir,
    save_metrics_csv,
    save_model_prediction_npz,
    save_training_history_csv,
    select_best_model_ids,
    timestamp_tag,
    write_json,
)
from .models import (
    MODEL_KEYS,
    NN_VARIANTS,
    AdaptiveBlackBoxODE,
    BlackBoxODE,
    ContinuousTimeESN,
    HybridFrozenPhysODE,
    HybridFrozenStribeckPhysODE,
    HybridJointODE,
    HybridJointStribeckODE,
    LinearPhysODE,
    StribeckPhysODE,
    StructuredBlackBoxODE,
    UDEODE,
    SequenceModelBase,
    GRUSeqModel,
    LSTMSeqModel,
    TCNSeqModel,
    MambaSeqModel,
    FeedForwardNN,
    build_model,
    extract_linear_params,
    extract_stribeck_params,
    iter_model_specs,
    load_model_checkpoint,
    model_label,
    save_model_checkpoint,
)
from .plots import (
    DEFAULT_COLORS,
    DEFAULT_STYLES,
    model_display_name,
    plot_acf,
    plot_predictions,
    plot_raincloud_models,
    plot_residuals,
    plot_spectra,
    plot_training_curves,
    plot_y_vs_yhat,
    plot_zoom_position,
)
from .train import (
    TrainConfig,
    compute_split_metrics,
    evaluate_model_on_dataset,
    set_global_seed,
    simulate_full_rollout,
    to_tensor_bundle,
    train_model,
)

__all__ = [
    "ExperimentData",
    "TrainRolloutData",
    "load_protocol2_datasets",
    "build_train_rollout_data",
    "compute_valid_start_indices",
    "summarize_protocol2",
    "MODEL_KEYS",
    "NN_VARIANTS",
    "LinearPhysODE",
    "StribeckPhysODE",
    "BlackBoxODE",
    "StructuredBlackBoxODE",
    "AdaptiveBlackBoxODE",
    "ContinuousTimeESN",
    "HybridJointODE",
    "HybridJointStribeckODE",
    "HybridFrozenPhysODE",
    "HybridFrozenStribeckPhysODE",
    "UDEODE",
    "SequenceModelBase",
    "GRUSeqModel",
    "LSTMSeqModel",
    "TCNSeqModel",
    "MambaSeqModel",
    "FeedForwardNN",
    "build_model",
    "extract_linear_params",
    "extract_stribeck_params",
    "iter_model_specs",
    "save_model_checkpoint",
    "load_model_checkpoint",
    "model_label",
    "TrainConfig",
    "to_tensor_bundle",
    "train_model",
    "simulate_full_rollout",
    "compute_split_metrics",
    "evaluate_model_on_dataset",
    "set_global_seed",
    "make_run_dir",
    "timestamp_tag",
    "save_training_history_csv",
    "save_metrics_csv",
    "aggregate_metric_rows",
    "select_best_model_ids",
    "write_json",
    "save_model_prediction_npz",
    "load_model_prediction_npz",
    "DEFAULT_COLORS",
    "DEFAULT_STYLES",
    "model_display_name",
    "plot_training_curves",
    "plot_predictions",
    "plot_zoom_position",
    "plot_residuals",
    "plot_raincloud_models",
    "plot_y_vs_yhat",
    "plot_acf",
    "plot_spectra",
]

# Optional exports for artifact conversion path (requires neural_ode_to_casadi).
try:
    from .artifact_pipeline import (
        compute_rollout_metrics,
        export_core_artifact,
        infer_model_kwargs,
        simulate_casadi_rollout,
        simulate_torch_rollout,
        validate_artifact_against_data,
    )
    from .id_wrappers import (
        BlackBoxIDWrapper,
        HybridFrozenPhysIDWrapper,
        HybridJointIDWrapper,
        LinearPhysIDWrapper,
        StribeckPhysIDWrapper,
    )

    __all__ += [
        "LinearPhysIDWrapper",
        "StribeckPhysIDWrapper",
        "BlackBoxIDWrapper",
        "HybridJointIDWrapper",
        "HybridFrozenPhysIDWrapper",
        "infer_model_kwargs",
        "export_core_artifact",
        "simulate_torch_rollout",
        "simulate_casadi_rollout",
        "compute_rollout_metrics",
        "validate_artifact_against_data",
    ]
except ModuleNotFoundError:
    pass
