"""Control System Identification Library."""

from .models import (
    ARIMA,
    GRU,
    HybridLinearBeam,
    HybridNonlinearCam,
    LSTM,
    LinearPhysics,
    NARX,
    NeuralCDE,
    NeuralNetwork,
    NeuralODE,
    NeuralSDE,
    RandomForest,
    StribeckPhysics,
    VanillaNODE2D,
    StructuredNODE,
    AdaptiveNODE,
    VanillaNCDE2D,
    StructuredNCDE,
    AdaptiveNCDE,
    VanillaNSDE2D,
    StructuredNSDE,
    AdaptiveNSDE,
    TCN,
    UDE,
    ExponentialSmoothing,
    Mamba,
)
from .data import Dataset
from .benchmarking import (
    BenchmarkCase,
    BenchmarkConfig,
    BenchmarkRunner,
    build_benchmark_cases,
    summarize_results,
)
from .visualization import (
    plot_predictions,
    plot_spectrograms,
    plot_residuals,
    plot_signals,
    plot_model_comparison,
)
from .validation import Metrics

__version__ = "0.1.0"
__all__ = [
    "NARX",
    "ARIMA",
    "NeuralNetwork",
    "NeuralCDE",
    "NeuralODE",
    "NeuralSDE",
    "ExponentialSmoothing",
    "RandomForest",
    "GRU",
    "LSTM",
    "TCN",
    "UDE",
    "Mamba",
    "HybridLinearBeam",
    "HybridNonlinearCam",
    "LinearPhysics",
    "StribeckPhysics",
    "VanillaNODE2D",
    "StructuredNODE",
    "AdaptiveNODE",
    "VanillaNCDE2D",
    "StructuredNCDE",
    "AdaptiveNCDE",
    "VanillaNSDE2D",
    "StructuredNSDE",
    "AdaptiveNSDE",
    "BenchmarkCase",
    "BenchmarkConfig",
    "BenchmarkRunner",
    "build_benchmark_cases",
    "summarize_results",
    "Dataset",
    "Metrics",
    "plot_predictions",
    "plot_spectrograms",
    "plot_residuals",
    "plot_signals",
    "plot_model_comparison",
]
